services:
  - type: web
    name: FreelanceHub
    env: python
    plan: free
    branch: main
    buildCommand: npm install && npm run build:css && pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
